# Generated by Django 3.2.2 on 2023-11-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0002_alter_trip_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='price',
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.PositiveIntegerField(default=100, max_length=100),
            preserve_default=False,
        ),
    ]
