# Generated by Django 4.0.6 on 2023-11-16 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0003_auto_20231110_0210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='space_left',
            new_name='trip_space',
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_offered', to='cargoapp.driver'),
        ),
    ]
