# Generated by Django 3.2.2 on 2023-11-10 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('phone', models.PositiveIntegerField(max_length=200)),
                ('driver_license', models.CharField(max_length=200)),
                ('passport_pic', models.ImageField(upload_to='images/')),
                ('national_id', models.CharField(max_length=200)),
                ('car_number', models.CharField(max_length=200)),
                ('car_picture', models.ImageField(upload_to='images/')),
                ('car_space', models.PositiveIntegerField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('departure_time', models.DateTimeField()),
                ('price', models.PositiveIntegerField(max_length=100)),
                ('space_left', models.PositiveIntegerField(default=5000, max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips_offered', to='cargoapp.driver')),
            ],
            options={
                'ordering': ['-departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.PositiveIntegerField(max_length=200)),
                ('full_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=100)),
                ('cargo_size', models.PositiveIntegerField(max_length=100)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargoapp.trip')),
            ],
        ),
    ]
